### ISSUE TITLE
Cannot call abstract method sfFacebookGuardAdapter::getUserProfileProperty()

### ISSUE THREAD

**Issue by jostster** [fabriceb/sfFacebookConnectPlugin#1]
Strict Standards: Non-static method sfFacebookGuardAdapter::getUserProfileProperty() should not be called statically, assuming $this from incompatible context in /home2/ameriee2/aksymfony/plugins/sfFacebookConnectPlugin/li b/sfFacebookApplicationFilter.class.php on line 25

Fatal error: Cannot call abstract method sfFacebookGuardAdapter::getUserProfileProperty() in /home2/ameriee2/aksymfony/plugins/sfFacebookConnectPlugin/lib/sfFacebookApplicationFilter.class.php on line 25

**Comment by fabriceb** [comment]
Corrected by your patch. Thanks
