### ISSUE TITLE
sfFacebookUser class removed

### ISSUE THREAD

**Issue by jostster** [fabriceb/sfFacebookConnectPlugin#3]
It seems that when you were cleaning up the code you removed the sfFacebookUser class which myUser is supposed to extend too.  The documentation says to still extend to sfFacebookUser in myUser but an error is thrown that the class cannot be found.

**Comment by fabriceb** [comment]
Yes, i removed it from the documentation, this extension was actually really not quite useful. But it did break backwards-comaptiblity on some projects. Sorry !
