### ISSUE TITLE
Fatal error: Class 'Facebook' not found on line 68

### ISSUE THREAD

**Issue by tristanbes** [fabriceb/sfFacebookConnectPlugin#4]
This is what i get after installing the plugin, set-up the right settings, and allow the application to access to facebook :

Fatal error: Class 'Facebook' not found in /Users/Tristan/Sites/SeekTeam/plugins/sfFacebookConnectPlugin/lib/sfFacebook.class.php  on line 68

Happens on URL :
http://xxxx/fb-connect/signin

**Comment by benja-M-1** [comment]
Hello,

The facebook API is included as a submodule in the plugin.
Did you make a "$ git submodule init" and "$ git submodule update" in the plugin directory ?

**Comment by tristanbes** [comment]
i didn't download the plugin via the console, i download the .zip archive on github, then put it on the plugin section.
If you could tell me exaclty how to install it correclty using the shell (because the .readme is kind of outdated and do not mention those parts).
Thanks

**Comment by benja-M-1** [comment]
You can download the php-sdk of facebook and add it in the lib/vendor directory of the plugin.

**Comment by tristanbes** [comment]
Thanks that fixed this problem. :)

**Comment by fabriceb** [comment]
git submodule init
git submodule update

It should be in the README :-)
