### ISSUE TITLE
Problem creating an user / updating : Constraint violation 

### ISSUE THREAD

**Issue by tristanbes** [fabriceb/sfFacebookConnectPlugin#5]
Hello,

After setting  up the plugin correctly and click on the facebook button got a constraint error (log here : http://pastie.org/private/x8n5gvyooqnj9yx5smhvq) :

case number one : 
- I already have an account and i want to associate the facebook to simplify the login process :

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`myproject`.`sf_guard_user_profile`, CONSTRAINT `sf_guard_user_profile_user_id_sf_guard_user_id` FOREIGN KEY (`user_id`) REFERENCES `sf_guard_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

You can see the YAML of the sfGuardUserProfile here : http://pastie.org/private/jbdxxcha4pd5wwrmccjpq

case number two : 

I want to create an user using the plugin.
1) I drop all the content of my table (sfGuardUser / Profile)
2) I click on the connect button : 

I've got the SAME error message, here are the logs from the debug bar : http://pastie.org/private/x8n5gvyooqnj9yx5smhvq

Is it happening only to me ? :O

**Comment by fabriceb** [comment]
I think it is linked to the multiple indexes and constraints you added in your schema which prevent the plugin to create the user and then the profile associated to the user.
