### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by chtipepere** [fabriceb/sfFacebookConnectPlugin#8]
Hi,

I'm using v1.1.1 since yesterday, and I can't logout a user connected with facebook.
I'm trying FB.logout(); and it doesn't work...
I still searching by my side, but if you can help me...
Thanks in advance.

**Comment by fabriceb** [comment]
I wrote a long answer and github logged me out :-(

So short summary : FB.logout() logs your user completely out of Facebook and not from your website. I guess it is not what you are looking for. You surely do not care about his facebook session and just want to to log him out of your website, therefore just : $sf_user->logout();

Cheers,

Fabrice

**Comment by chtipepere** [comment]
Thanks, 
But using the autoconnect filter make the user still connected.
So I'd like to logout hil completely from my website and from facebook.
That's why I'm trying to use FB.logout();
But when I call FB.logout(); the user still connected...

Here's what I'm trying to do :

<pre>...a href="SIGNOUT_SYMFONY_ROUTE" onclick="FB.logout(window.location.replace('SIGNOUT_SYMFONY_ROUTE')); return false;"...</pre>


Any idea ?

**Comment by fabriceb** [comment]
Ok I see, well it seems quite strange but more related to Facebook API (and its scarce documentation)...
Someone is having the same problem here : http://forum.developers.facebook.net/viewtopic.php?id=56568#p220846
